require_relative './automated_init'

module SettingMacro
  class Example
    setting :some_setting
  end
end

context "Attribute generated by the setting macro" do
  test "Has a getter" do
    example = SettingMacro::Example.new
    assert(example.respond_to? :some_setting)
  end

  test "Has a setter" do
    example = SettingMacro::Example.new
    assert(example.respond_to? :some_setting=)
  end
end
