module SettingMacro
  class Example
    setting :some_setting
  end
end

describe "Attribute generated by the setting macro" do
  specify "Has a getter" do
    example = SettingMacro::Example.new
    assert(example.respond_to? :some_setting)
  end

  specify "Has a setter" do
    example = SettingMacro::Example.new
    assert(example.respond_to? :some_setting=)
  end
end
